### ISSUE TITLE
Query pack to estimate a score for OS security in enrolled nodes

### ISSUE THREAD

**Issue by javuto** [jmpsec/osctrl#102]
OS security can be measured in each enrolled node by extracting information with queries. With a query pack this data can be aggregated and used for metrics.

**Comment by jhjacobs81** [comment]
Basic OS would be a priority over app security :) 
Maybe establish a baseline:
Endpoint protection enabled
Firewall enabled
Disk encryption enabled
No more then 5 important security updates missing
No more then 15 regular updates missing
No users enabled with weak or no password.
No “anonymous access” shares.
