### ISSUE TITLE
[Bug] Redirect users to an environment they have access to when logging in

### ISSUE THREAD

**Issue by logantn-dev** [jmpsec/osctrl#121]
The handler function that gets called after a user logs in always redirects users to the system-wide defaultEnv on the Osctrl server. 

Unfortunately, if the user does not have permissions to view/access the defaultEnv, they are sent to a blank page. This happens both if a user has access to no environments or any number of other, non-defaultEnvs. 

If they do not have access to any environments, they should have an error or message printed.

If they have access to $n other environments (none of which are the Osctrl server's defaultEnv), they should be redirected to https://IP_ADDR:8443/environment/ENV_NAME_THEY_CAN_ACCESS/active so they can view their environments.

**Comment by logantn-dev** [comment]
Link to code I believe would need to be changed: https://github.com/jmpsec/osctrl/blob/master/admin/handlers/get.go#L60

Also, thanks for the hard work on this tool, it is awesome!

**Comment by javuto** [comment]
Hey @logantn-dev thank you for using `osctrl` and happy new year! Yup this is indeed an issue and I hope to fix it for the `v0.2.5` release. There is another open issue for the same problem https://github.com/jmpsec/osctrl/issues/79

**Comment by logantn-dev** [comment]
Ah I did not see that one with the different phrasing of the issue. Thanks so much!!
