### ISSUE TITLE
build in (basic) OS management 

### ISSUE THREAD

**Issue by jhjacobs81** [jmpsec/osctrl#124]
OSQuery is per definition the ideal tool to gather information from a host. maybe write an extention to allow this information to be used to manage the host as well. this makes OSCTRL in league with tools like SCCM, DesktopCentral, Pulseway etc. 

For Windows this means the ability to execute powershell commands and/or modify the registry. for Linux this means modifying config files and/or execute bash commands.

**Comment by javuto** [comment]
For now, `osctrl` is not going to implement MDM capabilities.
