### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by javuto** [jmpsec/osctrl#13]
## Details

Currently osctrl does not have a `CONTRIBUTING.md` file that outlines details for contributions. Let's create one!

**Comment by shade34321** [comment]
Hey, I'd like to pick this up if possible though I'm not quite sure what is needed just yet.

**Comment by javuto** [comment]
Awesome! We can start gathering few examples of other `CONTRIBUTING.md` files, and turn this into the file: https://www.osctrl.net/contributing/

**Comment by shade34321** [comment]
Cool, Thanks!

**Comment by shade34321** [comment]
I'm not sure what you mean by "and turn this into the file". I've transplanted what that page has to a `CONTRIBUTING.md` file within the repo for an initial file. Is this what you meant? You can view it [here](https://github.com/shade34321/osctrl/blob/add_contribution_info/CONTRIBUTING.md).

Some other things I could think of that should be in there or would be useful.

Anything about code quality and/or standards?
Unit tests? Integration tests?
How to build?
How to run tests?
Is there a license agreement?
What's the bare minimum needed to work on this project? Compiler, versions, libraries, hardware requirements?
Are there any guidelines are PRs? Pass CI/CD?

I know some of these are answered by documentation which I'm still going through. But figured I'd put my thoughts here while I finish up the documentation.
