### ISSUE TITLE
Error setting default environment near completion of vagrant provisioning

### ISSUE THREAD

**Issue by monsrud** [jmpsec/osctrl#221]
Having some problems with getting either the vagrant provision or on OS provision to work. The recent repo has an error around setting the environment to the one the user has selected. When I look in postgres after the install, the settings table is empty. I went back and tried the vagrant setup on a couple of the tags and also on the revision at the end of october 2021. In that case, provision completes successfully but the user password given from the provisioning script can not log into the UI. If you have a specific revision that completes provisioning successfully, please let me know. I have not tried the docker version yet.  Maybe I should try that instead? I am just curious what the UI looks like and what some of the functionality is the osctrl provides. Thanks.

This is a screen of the error toward the very end of provisoning:
![image](https://user-images.githubusercontent.com/8558106/155018735-046a38d5-5434-4546-b3ab-1aa851935e8c.png)

Empty setting_values table after execution of provisioning script:
![image](https://user-images.githubusercontent.com/8558106/155019526-027d95cd-d714-4362-8205-65b981c5c543.png)

**Comment by javuto** [comment]
Hey @monsrud thank you for opening the issue and using osctrl! I am tracking down this issue and I will post updates here. I believe it is related to the migration to GORM 2. It should work fine before that code was merged, basically until a2a9b070ce7ef81906da0849823d09b3b6c083af. In any case I am actively working on this so it should be fixed in the next few days. Thanks again!

**Comment by javuto** [comment]
Just merged a PR that fixes the issue you saw. With `vagrant up` it should complete the deployment for a fully working osctrl environment including:
* `osctrl-tls` component to handle communication with osquery nodes.
* `osctrl-admin` component to handle the UI to administer osctrl.
* `osctrl-api` component to automate some actions via API.
* PostgreSQL backend
* Redis cache
* nginx as TLS terminator and load balancer.

Let me know if there is anything else I can help with. Thanks!
