### ISSUE TITLE
osctrl-tls clarity on enrollment error messaging

### ISSUE THREAD

**Issue by cmc** [jmpsec/osctrl#222]
checkValidEnrollSecretPath checks secret path + expiry time, but only throws an error message of:

 "handlers.go:582: Invalid secret path for enrolling"

This could be broken into 2 errors/warnings:

"handlers.go:582: Invalid secret path for enrolling"

and

"handlers.go:x: secret path for enrollment has EXPIRED"

https://github.com/jmpsec/osctrl/blob/295c51bd0d3ca74fb62f5a33272022b818ad4137/tls/handlers/utils.go#L45 <- func def
https://github.com/jmpsec/osctrl/blob/e125f318d84383d620178b7b8175044be69af6dd/tls/handlers/handlers.go#L587-L592 <- error handler.

osctrl-tls shows only that the path is invalid. the enrollment link also just fails silently. 

We should make it clearer _why_ the enrollment failed. It is not immediately obvious that the expiration is the issue. Endpoint for enrollment could even return "Expired" to caller.

**Comment by javuto** [comment]
Added more descriptive errors and now if the path or secret is invalid, `osctrl-tls` will return `Invalid` and if the link is expired, it will return `Expired`. Also if there is an error parsing the script, it will return `Error generating script`. Thank you for the issue!
