### ISSUE TITLE
Create links to query results for non DB logging

### ISSUE THREAD

**Issue by kosborn** [jmpsec/osctrl#26]
This may be superfluous with #19 coming down the pipeline. Nevertheless,  including a configurable link to the actual logging system with the query name included would be convenient. This could be achieved with simple variable substitution in a URL (`http://logs.example/search?q=name:${query_name}`). 

1) Determine if logging is set to something other than DB.
2) Add a button to /query/list that goes directly to a the search URL
3) Add a button or link somewhere on /query/logs/{query_id}

Stretch goal: include some absolute time variables based around the time that the query was initially kicked off so that we can easily get to older queries. Graylog uses ISO 8601 in the URL, so the url template would be: `https://graylog.example/streams/000000000000000/search?rangetype=absolute&from=${date_start}&to=${date_plus_1hour}&q=name:${query_name}`

**Comment by javuto** [comment]
Thank for creating this issue! This is definitely something I had in mind, and for Splunk the code is there, but I need to test it more. Let's get it done.

**Comment by javuto** [comment]
Implemented and merged! Now the links appear in result logs, result logs and queries. They can be fully customizable via `Admin Settings`.
