### ISSUE TITLE
Rotating user passwords

### ISSUE THREAD

**Issue by CptOfEvilMinions** [jmpsec/osctrl#268]
When rotating a user's password it doesn't ask the user for their current password to verify the requestor.

<img width="525" alt="Screen Shot 2022-05-26 at 12 53 53 AM" src="https://user-images.githubusercontent.com/35814920/170425614-1f5352c3-db3e-4763-9797-0f37a25c5f83.png">

**Comment by javuto** [comment]
Each user can set change their own password, and it does require the old password to be changed. But an admin can change the password for a user without the old one.
