### ISSUE TITLE
Can't enroll nodes.

### ISSUE THREAD

**Issue by jubinmytheen** [jmpsec/osctrl#309]
Installed osctrl using docker. But when trying to enroll the node, the enroll script is running successfully on the remote node. But it is not reflected on the osctrl. While checking the docker logs, we are getting the "enroll (Request error: certificate verify failed) retrying" error. May I know what is the issue with this?

**Comment by javuto** [comment]
Did you use the script `./deploy/docker/dockerize.sh` or any of the `Makefile` commands to create the docker environment?

**Comment by javuto** [comment]
Please take a look at the latest commits in https://github.com/jmpsec/osctrl/pull/341, it may help solve some of the docker issues. Thank you!

**Comment by javuto** [comment]
The `docker-dev` environment has been updated and many issues fixed. Please test it and if the issues persist, feel free to open a new issue. Thanks!

https://github.com/jmpsec/osctrl/pull/393
