### ISSUE TITLE
osctrl-admin sticky sessions

### ISSUE THREAD

**Issue by CptOfEvilMinions** [jmpsec/osctrl#372]
`osctrl-admin` requires the load balancer to use sticky sessions to allow for successful login. If multiple `osctrl-admin` instances are set up behind a load balancer using round robin for routing but WITHOUT sticky sessions as user can NOT login. When a user attempts to login the request is successful but the user is redirected to the login screen.

**Comment by javuto** [comment]
Sessions are stored in the database, so as long as every instance of `osctrl-admin` is connected to the same backend, sessions will be retrieved correctly. Now if you want to avoid having to create a new session when you are hitting a different endpoint which can not decode an existing JWT token (used in sessions), you need to look into having the same `--session-key` parameter in `osctrl-admin`, also loaded in the env variable `SESSION_KEY`: https://github.com/jmpsec/osctrl/blob/main/admin/main.go#L272

I presume this is the functionality you are looking for to avoid having to login again after a restart. 

Thank you and I hope this helps!
