### ISSUE TITLE
How Install OSCTRL in Ubuntu.

### ISSUE THREAD

**Issue by Rodasa** [jmpsec/osctrl#412]
Hello.
I'm trying to install osctrl on ubuntu 18.04 and 20.04 and I'm having the same problem. It tells me that it cannot find the postgressql-14 package.
I try to install it manually and it also fails. What would be a complete guide, step by step, to install it on Ubuntu or Debian? Thank you so much

**Comment by javuto** [comment]
Please take a look at https://github.com/jmpsec/osctrl/pull/413 and see if that fixes your issues. Thanks!

**Comment by javuto** [comment]
Also https://github.com/jmpsec/osctrl/pull/414

You should be good to go to install osctrl in Ubuntu 20.04 using the `provision.sh` script. I just tested it deploying nginx, postgres, redis and installing all components (admin, tls, api), in mode dev so it generates its own self-signed certificates:

```
./deploy/provision.sh -m dev -s ~/osctrl -p all --postgres --redis --nginx
```

It should also work in Debian 12, but I am afraid that Ubuntu 18.04 is not supported.
