### ISSUE TITLE
Getting enroll secret from osctrl-api endpoint

### ISSUE THREAD

**Issue by peterbogdan** [jmpsec/osctrl#459]
Hello

I want to enroll some osquery nodes using osctrl but I have a bit of an question of where can I get the secret for this.

I see that the secret is refreshed or extended from the UI but I would like to be able to get this from the API endpoint directly using a Token.

I tried to look into the API endpoints but I am a bit lost and could not find a path that could return this info for me?
Is it possible to get this information via the API? can anyone with more knowledge point me in the right place to look for that?

Thank you.

**Comment by peterbogdan** [comment]
Managed to get the info I need using the `/api/v1/environments/` endpoint.

But I see it has the the authorization permissions to read/write: https://github.com/jmpsec/osctrl/blob/main/osctrl-api.yaml#L393-L395

should that be the case if only retrieving this info?

**Comment by javuto** [comment]
Let me look into this and see what we can do

**Comment by peterbogdan** [comment]
hello @javuto 

Did you have some time to look into this?

**Comment by javuto** [comment]
I am updating the documentation for the API first, until that is done, please look in the code of `osctrl-api`, thanks!

**Comment by javuto** [comment]
Please check the up-to-date `osctrl-api` documentation in https://osctrl.net/openapi/doc.html

**Comment by javuto** [comment]
Implemented in #475
