### ISSUE TITLE
dbFlag & apiFlag incorrectly set on osctrl-cli env quick-add

### ISSUE THREAD

**Issue by peterbogdan** [jmpsec/osctrl#469]
Hello

Looks like the `dbFlag` and `apiFlag` are incorrectly set when calling `osctrl-cli env quick-add` [here](https://github.com/peterbogdan/osctrl/blob/34a171cc3674a2a8827bb67ead128eb21b4db5f5/cli/main.go#L1590)

Looking at the code this action queries the DB but looks like `apiFlag` is set to `true` and `dbFlag` should be set instead.

Could not figure out where in the code this is happening to create a PR.
I can see that the quick-add wrapper is set [here](https://github.com/peterbogdan/osctrl/blob/34a171cc3674a2a8827bb67ead128eb21b4db5f5/cli/main.go#L880-L880) but I do not see any reference to this flags so not sure where they are inherited from.

Durring some testing I presume some other commands (like `osctrl-cli settings show`) have this problem also because they result in a panic error:
```panic: runtime error: invalid memory address or nil pointer dereference```

**Comment by javuto** [comment]
Implemented in #476
