### ISSUE TITLE
extend/rotate quick-add enrollment secret using osctrl-api/osctrl-cli

### ISSUE THREAD

**Issue by peterbogdan** [jmpsec/osctrl#470]
Hello,

I want to be able to rotate or extend the enrollment secret used for the `enrroll.sh` scripts using the API or CLI but I could not find any command to do this.

Is there a command to update the secret or extend it's duration? Having to manually do this in the UI every 24h is a bit inconvenient for us.

Thank you.

**Comment by javuto** [comment]
Implemented in https://github.com/jmpsec/osctrl/pull/500
