### ISSUE TITLE
How to start the docker dev env

### ISSUE THREAD

**Issue by zhuoyuan-liu** [jmpsec/osctrl#493]
I am following the guide in https://github.com/jmpsec/osctrl/tree/main/deploy/docker to get started with osctrl. However, I keep getting errors when I start the docker-compose:

```
❌ Failed to execute - Failed to create backend - Failed to load DB configuration - open config/db.json: no such file or directory
```

Could you please explain where I should attach this config file?

**Comment by zhuoyuan-liu** [comment]
@javuto  I believe this change breaks the docker setup https://github.com/jmpsec/osctrl/pull/476/files

**Comment by javuto** [comment]
Fixed in https://github.com/jmpsec/osctrl/pull/496

You can build the docker environment with `make docker_dev_build` and bring it up with `make docker_dev_up``

Thank you!
