### ISSUE TITLE
Supporting prometheus or openmetrics

### ISSUE THREAD

**Issue by zhuoyuan-liu** [jmpsec/osctrl#504]
It would be great if we could support Prometheus or openmetrics to better integrate with other observability tools.

- https://openmetrics.io/
- https://prometheus.io/docs/guides/go-application/
- https://opentelemetry.io/docs/languages/go/

We are happy to contribute to this feature.

**Comment by javuto** [comment]
You have a preference between prometheus or openmetrics? There is an issue to add the `/metrics` endpoint to all services and to use prometheus (#273) but I don't like the model where those metrics need to be exposed. Technically there is nothing sensitive there but still. Thoughts?

**Comment by zhuoyuan-liu** [comment]
All our projects are using Prometheus and it just released their 3.0 last week.

- https://prometheus.io/docs/guides/go-application/
> I don't like the model where those metrics need to be exposed.
This information for sure should not be exposed publicly. It should only be exposed to internal service that can scrape the metrics. We can do it either have a different port for metrics service only or config nginx to only expose required paths.

**Comment by javuto** [comment]
Implemented in https://github.com/jmpsec/osctrl/pull/522 for `osctrl-tls`, more components will follow soon!
