### ISSUE TITLE
Osquery decorator for getting username

### ISSUE THREAD

**Issue by zhuoyuan-liu** [jmpsec/osctrl#534]
Hi @javuto , I can see that in the default setup, it uses the decorator `SELECT user || ' (' || tty || ')' AS username FROM logged_in_users WHERE type = 'user' ORDER BY time LIMIT 1;` to get the username of the node.

However, after our testing, it will always return empty results, and all last users shown `unknown`. Is there something updated with the query?

**Comment by javuto** [comment]
In macOS it extracts the user correctly, let me see if the decorator is not picket up by `osctrl-admin`

**Comment by javuto** [comment]
Tried in Ubuntu and also works as expected. So it must be an issue with the decorator not being processed as it should.

**Comment by javuto** [comment]
Merged the fix for the username, and other metadata fields, not being updated when logs were processed. Thank you!

https://github.com/jmpsec/osctrl/pull/538
