### ISSUE TITLE
No query results in DB

### ISSUE THREAD

**Issue by P1cker** [jmpsec/osctrl#546]
Hi all, I'm not receiving any scheduled query results in the backend database or the web UI. Is anyone else experiencing this issue?

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/37ceacb2-528d-4f3e-92dc-ca634c815a40">
<img width="1794" alt="image" src="https://github.com/user-attachments/assets/eea34a63-7776-41fb-95c7-2d24e2dee560">

The Web UI keeps showing 'Processing,' and there are no result data found in the 'osquery_result_data' table of the backend database.

I used the default Docker Compose configuration.

**Comment by javuto** [comment]
Do you see any errors in the logs? Check in the `osctrl-tls` or `osctrl-admin` containers. Thanks!

**Comment by javuto** [comment]
Are you using the `db` logger? Please check if the code in `main` still has this issue. Thanks!

**Comment by javuto** [comment]
I just confirmed both status and results logs are being written to the database, using the default docker dev environment. Please feel free to reopen with more information about this issue. Thank you!
