### ISSUE TITLE
Allow multiple loggers for osctrl-tls

### ISSUE THREAD

**Issue by javuto** [jmpsec/osctrl#65]
## Overview

Currently only one logger is allowed when shipping logs collected by `osctrl-tls`. It can be Splunk or Graylog, but only one, although db logger is always enabled, to keep a small window of logs in the backend (postgres).

It would be a good feature to enable the forwarding to multiple loggers, so logs can be replicated easily as they arrive.

**Comment by ewaher** [comment]
ty <3
