### ISSUE TITLE
Documentation for the API

### ISSUE THREAD

**Issue by crimsonknave** [jmpsec/osctrl#87]
I would love to see some docs on API endpoints. At a minimum a list of the urls, a list of parameters and a summary of the responses would be great. Right now it's pretty difficult to try and use the api as I don't write go, so digging into the code for the api is :grimacing:

**Comment by javuto** [comment]
Here is the documentation for all the supported endpoints in `osctrl-api` with the types and the format expected. Let me know if you want something else added to the API!

https://app.swaggerhub.com/apis-docs/jmpsec/osctrl-api/0.2.3
