### ISSUE TITLE
osctrl as an MSSP?

### ISSUE THREAD

**Issue by jhjacobs81** [jmpsec/osctrl#90]
So, we are looking for better tools then we currently have (Wazuh, works nice.. but its yugh in my opinion) and then i ran into osquery.. Seems nice :) doesnt seem yugh like Wazuh :) 

Now i wonder, could osctrl be be used for a small MSSP with multi tenants and alerting? (in some form, or another)
in the end we would also like reporting.. but first thing's first ;-)

**Comment by javuto** [comment]
Hey @jhjacobs81, I have been thinking about adding another component (`osctrl-alerts`) that handlers alerting as the data flow through `osctrl`, which is the moment you want your alerts to trigger. What would be the must-have for you to choose `osctrl`?

**Comment by jhjacobs81** [comment]
Define must-have please?

In the most basic, alerting per email would be nice.

We are a small MSSP trying to bring descent IT Security to the smb's, for a descent price :) So we fully understand that not every enterprise grade option will be available.

Is there a way for me to contact you per mail?
